library(TSA)
simdata1 = arima.sim(list(order= c(1,0,1), ar = c(0.6), ma = (-0.5)),n = 100)
plot(simdata1,type='o')
acf(simdata1)
par(mfrow=c(2,2))
simdata1 = arima.sim(list(order= c(1,0,1), ar = c(0.6), ma = (0.5)),n = 100)
plot(simdata1,type='o')
acf(simdata1)
simdata1 = arima.sim(list(order= c(1,0,1), ar = c(0.6), ma = (0.5)),n = 100)
plot(simdata1,type='o')
acf(simdata1)
simdata1 = arima.sim(list(order= c(1,0,1), ar = c(-0.6), ma = (0.5)),n = 100)
plot(simdata1,type='o')
acf(simdata1)
# making inferences for time series data is challening 